name: Compilar e publicar o PDF

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: thomasweise/texlive

    steps:
      - name: Checkout no repositório
        uses: actions/checkout@v2

      - name: Compilar e testar o LaTeX
        run: make

      -name: Upload do artefato
        uses: actions/upload-artifact@v2
        with:
          name: AurelioCarlosPradoSilva_curriculo.pdf
          path: "."

      -name: Publicação do PDF
        uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name: 'curriculo.pdf'
          file: 'curriculo.pdf'