name: Compile PDFs

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: thomasweise/texlive

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compile
        run: make

      - uses: actions/upload-artifact@v2
        with:
          name: AurelioCarlosPradoSilva_curriculo.pdf
          path: "."

      - uses: djnicholson/release-action@v2.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name: 'curriculo.pdf'
          file: 'AurelioCarlosPradoSilva_curriculo.pdf'      